### ISSUE TITLE
add strokes 

### ISSUE THREAD

**Issue by iceberg1369** [code-mc/loadtoast#10]
adding strokes to background makes it more beautiful

**Comment by ghost** [comment]
True. Sometimes its boundary is not clear when background is light or white.

**Comment by Daan-Hoogland** [comment]
+1

**Comment by lmbd** [comment]
+1

**Comment by code-mc** [comment]
I agree, but I'm not the best designer around so if you have a suggestion on color/stroke width etc that would be nice. Preferable by providing a mockup :)
