### ISSUE TITLE
align loadtoast

### ISSUE THREAD

**Issue by mlkmhd** [code-mc/loadtoast#14]
Hi,
thank you for this library. this is very good
I have a problem. when I am testing loadtoast on `android 4.4` it is showing in `center&top` of screen but on `android 4.0`, its align is `right&top` of screen. I want loadtoast be `center&top` always. also some time in `android 4.4` showing in `right&top`
how can i fix this problem?

**Comment by code-mc** [comment]
Would be helpful if you could provide some sample code so I can recreate this myself.

**Comment by mlkmhd** [comment]
I found the problem :+1:  
I am using `LoadToast` in a fragment. I was creating an instance of this class in `onActivityCreated` method in fragment and some time the align of `loadToast` was `right&top`. I don't know was actually happen but now I am creating that instance when i need (after click a button) and align of `loadToast` is `center&top`

thank you very much :-)

**Comment by code-mc** [comment]
Thanks, I'm going to check if I can do something so it does align properly when you init it in onActivityCreated.
