### ISSUE TITLE
loadtoast alignment is top right corner when used in a viewgroup

### ISSUE THREAD

**Issue by munimisu** [code-mc/loadtoast#21]
I am using loadtoast in viewpager and when displaying loadtoast, its aligned to top right instead of middle top. 

How can i make it to display normally in middle?

**Comment by code-mc** [comment]
Encountered the same issue myself today, I'll see if there is a way to center in "ViewGroup". Wrapping the ViewPager inside e.g. a RelativeLayout would fix it I'm pretty sure.

**Comment by munimisu** [comment]
Any fix for this? Thanks.

**Comment by code-mc** [comment]
b3271a700c9f18fa51fbc968e5416577938b2d14 Haven't been able to reproduce so I'm assuming this is fixed with the latest changes.
