### ISSUE TITLE
LoadToast leaking activities?

### ISSUE THREAD

**Issue by veelck** [code-mc/loadtoast#23]
Hi,

I did some benchmarking and it seems, that somewhere inside the NineOldAndroid's the listeners are not released properly, causing whole activities leaking.

Here is the sample path to GC root
## Class Name                                                                             | Ref. Objects | Shallow Heap | Ref. Shallow Heap | Retained Heap

java.lang.Thread @ 0x89418f80  main Thread                                             |            9 |           88 |             3,312 |         3,400
'- localValues java.lang.ThreadLocal$Values @ 0x8b1fa718                               |            9 |           32 |             3,312 |         2,024
   '- table java.lang.Object[64] @ 0x12c50d40                                          |            9 |          272 |             3,312 |         1,992
      '- [59] java.util.ArrayList @ 0x12e3e720                                         |            9 |           24 |             3,312 |           112
         '- array java.lang.Object[18] @ 0x12dc1a60                                    |            9 |           88 |             3,312 |            88
            |- [3] com.nineoldandroids.animation.ValueAnimator @ 0x12d3cc10            |            1 |           96 |               368 |           752
            |  '- mUpdateListeners java.util.ArrayList @ 0x12c99400                    |            1 |           24 |               368 |           104
            |     '- array java.lang.Object[12] @ 0x12c9b7c0                           |            1 |           64 |               368 |            80
            |        '- [0] net.steamcrafted.loadtoast.LoadToastView$1 @ 0x12c03fc0    |            1 |           16 |               368 |            16
##             |           '- this$0 net.steamcrafted.loadtoast.LoadToastView @ 0x132e8400|            1 |          576 |               368 |         1,160

Let me know if you need any more info.

**Comment by code-mc** [comment]
Seems like this is something that happens more often with nineoldandroids. I'll try find some time to look into it. If you'd find a fix yourself please do a pull request!

Issue seems to be the animationlistener that is registered that is leaking.
