### ISSUE TITLE
Show from the bottom

### ISSUE THREAD

**Issue by vpratfr** [code-mc/loadtoast#6]
Would be nice to be able to tell the toast to show from the bottom instead of from the top.

My UI has some important elements on top and it would be better to have the toast slide in from the bottom of the screen

**Comment by code-mc** [comment]
Fork it, there already is a fork that does this.

**Comment by vpratfr** [comment]
@code-mc  Why not offering both possibilities. Looks like you simply have to merge the changes from https://github.com/geralt-encore/loadtoast/commit/3f5ac5d8ef325f1c1301159618aec4eba0983832  

Would you include the changes if I submit a pull request allowing to choose between top or bottom, defaulting to top?
