### ISSUE TITLE
Does not disappear in some cases

### ISSUE THREAD

**Issue by vpratfr** [code-mc/loadtoast#7]
When `show()` and `success()` are called within a very short time frame, it looks like the toast is not dismissed. 

This happens for instance in my loader when data is cached (calling show when starting the loader but that one gets completed within 10ms and thus I call success() really quick).

**Comment by Daan-Hoogland** [comment]
+1, got the same issue

**Comment by Tebra** [comment]
+1, same issue here. 

Had to call success() twice after show() for it to change state, but it didn't disappear.

**Comment by stripathi669** [comment]
+1 same issue here. Anyone found solution ?

**Comment by code-mc** [comment]
Fixed in v1.0.8, sorry for the delay, I hope you found it yourself :)
