### ISSUE TITLE
Adjust width according to text length

### ISSUE THREAD

**Issue by vpratfr** [code-mc/loadtoast#8]
- If the text is too long for the fixed width, the text gets cut. The toast should either 
  - marquee the text (scroll it from right to left)
  - adjust the width of the toast (up to screen width minus some margin)
  - split text on multiple lines

**Comment by sweggersen** [comment]
+1

**Comment by mustafa-demir** [comment]
+1

**Comment by code-mc** [comment]
I have incorporated you suggestion. The text will now marquee if it doesn't fit the toast. (v1.0.7)
