### ISSUE TITLE
Handle cases without text

### ISSUE THREAD

**Issue by vpratfr** [code-mc/loadtoast#9]
If there is no text, the LoadToast should just show the progress loader without any empty space on the left.

Sometimes we don't want to write anything, just show that something is getting done in the background.

**Comment by dmallcott** [comment]
Came here to post this. I would love to have this feature.

**Comment by code-mc** [comment]
I'm going to include this in the next release. I've been busy with school work so I didn't have much time to work on this project.

**Comment by code-mc** [comment]
v1.0.8 includes this terrific suggestion!
